### PR TITLE
Add clean action

### PR DESCRIPTION
**Pull request by david30xie**
- Add -C action
- use .construi.yml to store all created images

### CODE REVIEW

**Comment by lstephen** [comment]
Could you expand on the use case for this feature?

**Comment by david30xie** [comment]
when you run `docker images` command, you will see lots of images start with `construi_`, and there are times you want to remove them for so many reasons, like

1. Save some space
2. This project is done, need to do some clean up
3. Got new version of project, clean up old images
4. ...

Anyway, for whatever reason, user may want to remove these images, of course they can use `docker rmi`, but it'll be better if we provide a command to do so.

What do you think?

**Comment by lstephen** [comment]
In general, running out of space because of collecting images over time is an issue for docker (hence numerous tools along these lines exist: https://github.com/spotify/docker-gc). This makes it tempting to say image management is out of scope for construi. But construi probably does have a different usage pattern to many docker usages, in that it's designed for being run multiple times, rather than as a long running process, which means it's creating images at a faster rate than other tools.

Hopefully behavior is consistent with `docker-compose run --rm` (https://docs.docker.com/compose/reference/run/), but that deals with containers rather than images.

Rather than a separate clean task, I think perhaps this is better as a command line option (e.g., --keep-images, or --remove-images), and the image is cleaned or not after the run.

**Comment by lstephen** [comment]
I bumped the docker-compose version in #120. Since this PR reminded me I hadn't done it in a while 👍

**Comment by david30xie** [comment]
aha. Good.

I would say let's keep this action, even I am the only user who needs it, because there's no harm to have one new feature.

And for `--keep-images` is a good idea. What I would do is create a parameter called `--remove-image`, and set it to `false` by default. When user turns it on, delete this image after finishing target.

**Comment by lstephen** [comment]
I don't think the added complexity of adding this feature is worth the benefits.

Cleaning multiple images seems simple enough using a docker gc app (such as the spotify one linked above), or even using a bash 1-liner:

```
docker images | grep construi | awk '{print $1 ":" $2}' | xargs docker rmi
```

I will look into adding the `--remove-image` cli option.

Is the left over image an issue with all runs, or just those that use 'build' rather than 'image'?

**Comment by david30xie** [comment]
Actually, the command you provided is not 100% correct. If you check my PR carefully you will find that I am using `.construi.yml` to keep images construi created for this project.

If you grep images just by `construi`, you will delete images which belong to other projects.

**Comment by lstephen** [comment]
Right, but keeping around images for construi is not useful. A new id is generated on each run, so images are never re-used. So, I'm not sure 'I need to delete images for a project' vs 'I need to delete images' is worth differentiating.

If it's useful to associate images with a project, then I'd rather include the project name in the image id, rather than maintaining that info in a file (that can get deleted/corrupted, etc).

**Comment by lstephen** [comment]
The `docker-compose down` command has an `--rmi` option, suggesting there is code there that could be used to implement the deleting of images after a construi run.

**Comment by lstephen** [comment]
Closing.

Removing images means that the advantages of docker caching during builds is lost.

To prevent proliferation of random images #122 was implemented so that random ids are not used in image names.

**Pull request closed without merging**
